Make changes to solve the problems with AOT compilation and deploy (#21)
* Make changes to solve the problems with AOT compilation and deploy
examples app to Firebase

**Why was this change made?**
To solve the following problems with AOT compilation:

Problem:
-Function calls inside the module metadata in DocLib module's static
forRoot function is causing following error which is not useful for
debugging:
ERROR: Function calls are not supported in decorators.
https://www.bennadel.com/blog/3565-providing-module-configuration-using-forroot-and-ahead-of-time-compiling-in-angular-7-2-0.htm

Workaround:
-Use a factory function declared outside the ngModule and call the
constructor 'new' function of doc retriever service inside that. And use
a intermediate injection token to provide the deps required for creation of the factory object.

Problem:
-Importing from barrels within a library is causing the following error:
ERROR in Unexpected value 'undefined' imported by the module
https://github.com/angular/angular/issues/23713

Workaround:
-Within the library packages, I am not importing files from barrels.
Instead they are being imported from absolute paths.

Problem:
-Loading of routes in the existing way is causing following error:
ERROR in Cannot read property 'loadChildren' of undefined
https://stackoverflow.com/questions/44233195/dynamically-adding-routes-in-angular

Workaround:
-Use resetConfig in appComponent to reset the routes instead of setting them in app routing module

Problem: This happens in the web browser
-Documentation JSONS being provided from app component are becoming null inside the doc lib module utilizing them

Workaround:
-Assign the doc jsons imported to exported variables before calling the module static forRoot function with them

**Testing Done:**
-Deployed the app to a Firebase end point at https://vcdcc-examples-app.firebaseapp.com
-Verified that the bundle size is smaller than the one being downloaded
during development
-Verified that the app at the end point works as expected

**Bug Number:**
https://jira.eng.vmware.com/browse/VDUCC-46

Signed-off-by: ps37 <prudhvi.af121@gmail.com>