Publishing ui-components with rxjs version 6.5.5
We updated ui-components rxjs version to 7.4.0 but in vcd-ui that version causes a lot
of breaking changes which will need to be handled in a separate future time slot.

- vcd-ui currently uses rxjs@6.6.3 and wherever the SubscriptionTracker is used there errors:
"TypeError: _a.bind is not a function"
"TypeError: fn.call is not a function"
- 731 unit tests are also failing

- The simplest solution is to revert to the previous rxjs version that ui-components used - 6.5.5
- This fixes all the above mentioned issues

[publish @vcd/ui-components]

Signed-off-by: Georgi Atanasov <georgi.atanasov147@gmail.com>